"""add_audit_logs_table

Revision ID: b669f56cdac7
Revises: 4f3c22038863
Create Date: 2026-05-11 08:15:10.554410

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b669f56cdac7"
down_revision: Union[str, Sequence[str], None] = "4f3c22038863"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
