"""add_organizations_table_and_fks

Revision ID: f6f34ef9e5bd
Revises: c3f8a1b2d4e5
Create Date: 2026-06-03 19:53:02.418670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6f34ef9e5bd"
down_revision: Union[str, Sequence[str], None] = "c3f8a1b2d4e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column(
            "org_type",
            sa.Enum("HEADQUARTERS", "BRANCH", "SITE_OFFICE", "MOBILE", name="orgtype"),
            nullable=False,
        ),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "retention_policies",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("document_type", sa.String(), nullable=True),
        sa.Column("retention_years", sa.Integer(), nullable=False),
        sa.Column("is_permanent", sa.Boolean(), nullable=True),
        sa.Column("auto_archive", sa.Boolean(), nullable=True),
        sa.Column("auto_delete", sa.Boolean(), nullable=True),
        sa.Column("archive_grace_days", sa.Integer(), nullable=True),
        sa.Column("legal_basis", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("resource_type", sa.String(), nullable=True),
        sa.Column("resource_id", sa.String(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("sequence_number", sa.Integer(), nullable=True),
        sa.Column("record_hash", sa.String(), nullable=True),
        sa.Column("prev_hash", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_resource_type"),
        "audit_logs",
        ["resource_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_sequence_number"),
        "audit_logs",
        ["sequence_number"],
        unique=False,
    )
    op.create_table(
        "consent_records",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("consent_type", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("disclosed_purpose", sa.Text(), nullable=True),
        sa.Column("disclosed_retention_period", sa.String(), nullable=True),
        sa.Column("disclosed_third_parties", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consent_records_consent_type"),
        "consent_records",
        ["consent_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consent_records_created_at"),
        "consent_records",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consent_records_user_id"), "consent_records", ["user_id"], unique=False
    )
    with op.batch_alter_table("documents") as batch_op:
        batch_op.add_column(
            sa.Column("pdfa_validation_result", sa.JSON(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "timestamp_verified_at", sa.DateTime(timezone=True), nullable=True
            )
        )
        batch_op.add_column(sa.Column("timestamp_hash", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("timestamp_token", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("timestamp_tsa_url", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("retention_policy_id", sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("retention_expires_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("is_archived", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "deletion_requested_at", sa.DateTime(timezone=True), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("iso19650_originator", sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("iso19650_functional_breakdown", sa.String(), nullable=True)
        )
        batch_op.add_column(sa.Column("iso19650_form", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("iso19650_discipline", sa.String(), nullable=True)
        )
        batch_op.add_column(sa.Column("iso19650_number", sa.String(), nullable=True))
        batch_op.create_foreign_key(
            "fk_documents_retention_policy",
            "retention_policies",
            ["retention_policy_id"],
            ["id"],
        )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.add_column(sa.Column("organization_id", sa.String(), nullable=True))
        batch_op.create_foreign_key(
            "fk_projects_organization", "organizations", ["organization_id"], ["id"]
        )
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(sa.Column("organization_id", sa.String(), nullable=True))
        batch_op.create_foreign_key(
            "fk_users_organization", "organizations", ["organization_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_constraint("fk_users_organization", type_="foreignkey")
        batch_op.drop_column("organization_id")
    with op.batch_alter_table("projects") as batch_op:
        batch_op.drop_constraint("fk_projects_organization", type_="foreignkey")
        batch_op.drop_column("organization_id")
    with op.batch_alter_table("documents") as batch_op:
        batch_op.drop_constraint("fk_documents_retention_policy", type_="foreignkey")
        batch_op.drop_column("iso19650_number")
        batch_op.drop_column("iso19650_discipline")
        batch_op.drop_column("iso19650_form")
        batch_op.drop_column("iso19650_functional_breakdown")
        batch_op.drop_column("iso19650_originator")
        batch_op.drop_column("deletion_requested_at")
        batch_op.drop_column("archived_at")
        batch_op.drop_column("is_archived")
        batch_op.drop_column("retention_expires_at")
        batch_op.drop_column("retention_policy_id")
        batch_op.drop_column("timestamp_tsa_url")
        batch_op.drop_column("timestamp_token")
        batch_op.drop_column("timestamp_hash")
        batch_op.drop_column("timestamp_verified_at")
        batch_op.drop_column("pdfa_validation_result")
    op.drop_index(op.f("ix_consent_records_user_id"), table_name="consent_records")
    op.drop_index(op.f("ix_consent_records_created_at"), table_name="consent_records")
    op.drop_index(op.f("ix_consent_records_consent_type"), table_name="consent_records")
    op.drop_table("consent_records")
    op.drop_index(op.f("ix_audit_logs_sequence_number"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("retention_policies")
    op.drop_table("organizations")
    # ### end Alembic commands ###
